# Generated by Django 5.1.2 on 2024-10-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('talle', models.CharField(max_length=15)),
            ],
        ),
    ]
