# Generated by Django 5.1.2 on 2024-10-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropa',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='ropa',
            old_name='talle',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='ropa',
            old_name='tipo',
            new_name='tipe',
        ),
    ]
