# Generated by Django 5.1.2 on 2024-10-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_marca_ropa_brand_rename_talle_ropa_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropa',
            old_name='tipe',
            new_name='type',
        ),
    ]
